// // https://core.telegram.org/bots/api#promotechatmember
// struct PromoteChatMember {
//     chat_id: i64,
//     user_id: i64,
//     is_anonymous: Option<bool>,
//     can_manage_chat: Option<bool>,
//     can_delete_messages: Option<bool>,
//     can_manage_video_chats: Option<bool>,
//     can_restrict_members: Option<bool>,
//     can_promote_members: Option<bool>,
//     can_change_info: Option<bool>,
//     can_invite_users: Option<bool>,
//     can_post_messages: Option<bool>,
//     can_edit_messages: Option<bool>,
//     can_pin_messages: Option<bool>,
//     can_post_stories: Option<bool>,
//     can_edit_stories: Option<bool>,
//     can_delete_stories: Option<bool>,
//     can_manage_topics: Option<bool>,
// }
