[package]
name = "telegram"
edition = "2021"
version = "0.0.1"
talegram-version = "7.0"

[[example]]
name = "bot"
path = "examples/bot.rs"

[[example]]
name = "playground"
path = "examples/playground.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockito = "1.2.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = {  version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
serde_qs = "0.12.0"
serde_with_macros = "3.6.0"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }

# [minimal]
openssl = { version = "0.10.55", optional = true }
libgit2-sys = {  version = "^0.16.2", optional = true }
